server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmats
    username: root
    password: 146030
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .ftl
  freemarker:
    allow-request-override: true
    allow-session-override: true
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/pages/
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      classic_compatible: true
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.deloitte.cmats5.entity
#debug: true
#logging:
#  level:
#    root: info
#    com.deloitte.cmats5.mapper: debug
#    #tk.mybatis: debug
#  #config: classpath:/logback-spring.xml
#  #path: C:/ideaLog/
#  file: C:/ideaLog/cmats5.log
#  #pattern:
#  #    console: "%d - %msg%n"
